### ISSUE TITLE
feat/ref:Split socketwrapper.hpp into multiple header files

### ISSUE THREAD

**Issue by tglane** [tglane/socketwrapper#2]

**Comment by tanja84dk** [comment]
Sorry to ask is your plan to then only have splitted up files?
The reason I ask is because then I have to look for another library to use ( have never been able to get cmake to include libraries there use multiple files because I always have to recreate cmakelist files )

And I do know you dont supply a cmakelist file but its will give me so much headace that I have to find another solution

And I hope its okay for my question

**Comment by tglane** [comment]
> Sorry to ask is your plan to then only have splitted up files?
> The reason I ask is because then I have to look for another library to use ( have never been able to get cmake to include libraries there use multiple files because I always have to recreate cmakelist files )
> 
> And I do know you dont supply a cmakelist file but its will give me so much headace that I have to find another solution
> 
> And I hope its okay for my question

Hey i appreciate your question/comment.
The plan is to split the library into multiple **header** files because currently you have to include **and** compile all of the stuff inside the really big single header every time you include it.
But i think there shouldnt be any issues to use it because its still header only. Just put the directory `socketwrapper` under include in the repo (currently not on the main branch but on `ref/split-files`) in your include path of your project and include the headers you need. The readme on the branch is also updated to show which header is needed for which classes.

**Comment by tanja84dk** [comment]
> But i think there shouldnt be any issues to use it because its still header only. Just put the directory `socketwrapper` under include in the repo (currently not on the main branch but on `ref/split-files`) in your include path of your project and include the headers you need. The readme on the branch is also updated to show which header is needed for which classes.

Unfortunally that is not possible for me because I'm both building on Windows and Linux ( I always build on native and not mingw) so everything needs to be controlled from the projects cmakelist file

That's why everything in my projects has their own cmakelist file etc ( also folder structure ) to load the libraries in

And also if I just included the files then I would violate the gpl license because I do not agree with them ( using mit license myself )

And the workaround for the license issue for me that I know of is then to include gpl's as dynamic library.

Also if I just added it in my include folder then it would be difficult to keep track of the license files for each include


But thank you very much for your quickly response, and I will see if I'm able to find a way around the license issues for me.
Wishing you a really great day

**Comment by tglane** [comment]
Hmm i dont know how you are building stuff on windows but this lib is only working on linux (probably mac/bsd) because it uses the posix sockets provided by linux as stated in the readme. Though i dont know if there are wrappers for windows or something like that.

And yeah i chose the license back when i had no real clue what this means :D so yeah there are licenses that would suite better than the GPL i agree.

Thans! I wish you a nice day too and thank you for looking at my lib and commenting. Really appreciate it!
